### PR TITLE
add mpi_barrier

### PR DESCRIPTION
**Pull request by PhilipVinc**
I needed it for a recent bug hunt uncovering a deadlock in some code.

In this PR it is implemented  by memcpying the data in the input buffer to the output buffer, 
but maybe it would be more sensible not do to this and only play with tokens?

However, you cannot thread tokens everywhere: in the code I was investigating, which is a jax function performing `matmul` inside of a `jax.scipy.sparse.cg`, you cannot really thread tokens, instead the data dependency must be encoded in the arrays themselves...

Maybe we should have two versions of Barrier, one acting on tokens and the other on arrays? what do you think?

### CODE REVIEW

**Comment by dionhaefner** [comment]
How about we make a deal - you review mpi4jax/mpi4jax-joss#1 while I review this? :)

**Comment by PhilipVinc** [comment]
Sorry for ghosting you.
Yep i'm in for the deal

**Comment by dionhaefner** [comment]
To be honest I don't really understand the use case here.

First of all, do you have an example where barrier is helpful with debugging?

Second, when can't you thread a token? Maybe a short code snippet would make it easier to get on the same page.

**Comment by PhilipVinc** [comment]
imagine having

```python
from flax import struct
import mpi4jax
from mpi4py import MPI

mpi_size = MPI.COMM_WORLD.Get_size()

@struct.dataclass
class DistributedMatrix:
	local : jnp.ndmatrix

	@property
	def shape(self):
		return (self.local[0], self.local[1]*mpi_size)

	def __matmul__(self, vec):
	assert vec is a vector

		res, token = mpi4py.allreduce(self.local@vec, op=MPI.SUM)	
		return res

	def __call__(self, vec):
		return self @ vec


mat = DistributedMatrix(jnp.random.random(10,10))
vec, _ = mpi4jax.bcast(jnp.random.uniform(10*mpi_size), root=0)

jax.scipy.sparse.cg(mat, vec)
```

**Comment by PhilipVinc** [comment]
`jax.sparse.linalg.cg` expects you to provide a callable that returns a transformed vector/pytree with the same shape as the input.
You cannot return a token...

**Comment by dionhaefner** [comment]
I would solve this by introducing just a little bit of state: (similar to #59)

```python
@struct.dataclass
class DistributedMatrix:
	local : jnp.ndmatrix
        _current_token: Optional[jax.abstract_arrays.AbstractToken]

        @contextmanager
        def token_ctx(self):
            self._current_token = jax.lax.create_token()
            try:
                yield
            finally:
                self._current_token = None

	def __matmul__(self, vec):
		res, self._current_token = mpi4py.allreduce(self.local@vec, op=MPI.SUM, token=self._current_token)	
		return res

	def __call__(self, vec):
		return self @ vec


mat = DistributedMatrix(jnp.random.random(10,10), None)
vec, _ = mpi4jax.bcast(jnp.random.uniform(10*mpi_size), root=0)

with mat.token_ctx():
    jax.scipy.sparse.cg(mat, vec)
```

Yes, it's a bit ugly. But having 2 sets of primitives seems really awkward...

**Comment by dionhaefner** [comment]
I removed the array dependency on barrier for now so we can go ahead and merge this and figure out the rest later. 

I agree that tokens are a recurring problem and sometimes a pain to handle. Especially in something like a CG solver that has a fixed function signature.

It might pay off to ask the JAX people for a way to handle tokens in `fori_loop` / `while_loop`, which is what CG is based on...

**Pull request merged**
