### PR TITLE
[WIP] attempt to define AD primitives for Send/Recv

### PR DESCRIPTION
**Pull request by PhilipVinc**

### CODE REVIEW

**Comment by dionhaefner** [comment]
What was wrong with the backwards implementation?

We could consider supporting only forwards mode if that worked.

**Comment by PhilipVinc** [comment]
Send has no output, over than the token, which you cannot return from the function.
When you compute reverse-mode AD, you start from the output, and you transpose everything to handle the tangents.
But since send has no output that escaped the function, you don't have the tangent for it's output and it's backward pass is culled away.

This in general is useful, because if you write
```python
def f(x,y)
   ...
   return val1, val2

def g(x,y):
   return sum(f(x,y)[0])

jax.grad(g)(x,y)
```

you already know that in the backward pass you don't need to compute the backward pass of val2, because that does not contribute to the output.
But in our case this breaks the reverse pass

**Comment by PhilipVinc** [comment]
I should put back the forward pass though

**Comment by dionhaefner** [comment]
It's OK for me if you don't add it back. Forward diff is less useful anyway and it just creates more code to maintain and test.

I think only supporting `sendrecv` is a good compromise.

**Pull request closed without merging**
