### PR TITLE
Port to MLIR

### LINKED ISSUE #176: Incorrect AlltoAll behavior in jitted function
First of all, thanks for this really great project! I am very much looking forward to using it for building a jax-based distributed cosmological N-body simulation (https://github.com/DifferentiableUniverseInitiative/JaxPM). 
I'm encountering a very strange issue though when trying to JIT functions, which I can boil down to the minimum working example I present bellow involving preforming an AlltoAll collective to transpose an array:

```python
from mpi4py import MPI
import jax
import jax.numpy as jnp
import mpi4jax

# Create communicators
world = MPI.COMM_WORLD
rank = world.Get_rank()
size = world.Get_size()

# Gobal size of 2D array
shape = [256, 256]

# Create a slice of the 2D array on each process
master_key = jax.random.PRNGKey(42)
key = jax.random.split(master_key, size)[rank]
local_slice = jax.random.normal(key, [shape[0]//size, shape[1]])

@jax.jit
def transpose(arr):
    # Split the last dimension in how many processes we have
    arr = arr.reshape([shape[0]//size, size, shape[1]//size])
    arr = arr.transpose([1, 0, 2]) # Move the number of slices to first dimension
    arr, token = mpi4jax.alltoall(arr, comm=world)
    # Merge the collected slices of the first dimension
    arr = arr.reshape([shape[0], shape[1]//size]) 
    arr = arr.transpose([1,0]) # Moves the unsliced dimension to the end
    return arr, token

# Perform the transpose
transposed_slice, token = transpose(local_slice)

# Let's make sure we have waited for all computations to be done
token = mpi4jax.barrier(token=token)

# Let's check that the results are OK
transposed_array, token = mpi4jax.allgather(transposed_slice, comm=world, token=token)
transposed_array = transposed_array.reshape(shape)
total_array, token  = mpi4jax.allgather(local_slice, comm=world, token=token)
total_array = total_array.reshape(shape)

print("On rank %d, here is the result: "%rank, 
      jnp.abs(total_array.transpose([1,0]) - transposed_array).mean())
```

If the `transpose` function is jitted, the output on a 4 process mesh is:
```bash
$ srun python test_mpi4jax.py 
On rank 0, here is the result:  1.1207631
On rank 1, here is the result:  1.1207631
On rank 3, here is the result:  1.1207631
On rank 2, here is the result:  1.1207631
```

If I remove the jitting on that function, I get the expected behavior showing that the transpose is correctly computed:
```bash
$ srun python test_mpi4jax.py 
On rank 0, here is the result:  0.0
On rank 1, here is the result:  0.0
On rank 2, here is the result:  0.0
On rank 3, here is the result:  0.0
```
This example was run using jax v0.3.23, and mpi4jax v0.3.10.post6, and I also tried to revert back to a jax version from this summer, without much difference. I only tried on GPU but it appears to be unaffected by the use of CUDA-aware MPI or not. But enabling debug mode I can see that the communications do occur as expected.

Very interestingly, I noticed that if I tweak the code in the following way:
```python
@jax.jit
def transpose(arr):
    arr = arr.reshape([shape[0]//size, size, shape[1]//size])
    arr = jnp.einsum('ij,xjy->ixy', jnp.eye(size), arr) # instead of arr.transpose([1, 0, 2])
    arr, token = mpi4jax.alltoall(arr, comm=world)
    return arr, token

arr, token = transpose(local_slice)
arr = arr.reshape([shape[0], shape[1]//size]) 
transposed_slice = arr.transpose([1,0]) 
```
i.e. replacing the first `jnp.tranpose` by an equivalent but more complex op involving an `einsum` gives me the correct results. So I don't think there is something intrinsically wrong with mpi4jax, but something weird going on with the input and output buffers of the collective op, for lax particular ops.

This makes me think that the physical memory layout of the buffer at the output of the transpose op doesn't actually correspond to its theoretical shape, which may be some optimization done by XLA to prevent moving the memory layout back and forth between operations.

I'm not sure how to debug this further, any help or insight would be much appreciated! I'll continue to poke around anyway because I really really want to use mpi4jax for my application ^^

### PR DESCRIPTION
**Pull request by dionhaefner**
Also adds consistent layouts for all operands.

Fixes #176 #150

### CODE REVIEW

**Comment by dionhaefner** [comment]
So far I've only done `allgather`. I wanted to make sure that this works before porting everything. @EiffL could you give this a spin on GPU? I don't have access to one at the moment.

**Comment by dionhaefner** [comment]
😬 worked on my machine

**Comment by EiffL** [comment]
Very happy to take a look and run in GPUs this evening :-)

**Comment by dionhaefner** [comment]
🤦 Tests where using the old JAX 0.3.24, hence the crash (segfault as reported in #178).

**Comment by PhilipVinc** [comment]
So we should bump the minimum jax version after this.

**Comment by PhilipVinc** [comment]
Let's drop everything old?

**Comment by PhilipVinc** [comment]
I would drop older releases and require 0.3.25 (and throw an informative error [here](https://github.com/mpi4jax/mpi4jax/blob/55b1307d4e4fd747cdd612abbd88f5c6cee4db0c/mpi4jax/_src/jax_compat.py#L59) if an older version of jax is installed). This also allows us to remove some of those checks for versions that require effects...

Jax has not been breaking too many things recently  so I don't mind dropping support for older versions.

**Comment by EiffL** [comment]
I apparently broke my dev environment on my gpu machine :facepalm: I havent been able to test it, but looking at the PR it does look very good.
The alternative to dropping <v0.3.25 is a lot of compatibility code... 

One approach (which I'm not necessarily advocating for) would be to merge my hack that ensure correct code behavior on jax <= v0.3.24, and tag a release which would become the last release of mpi4jax compatible with earlier jax versions. People who can't upgrade jax to 0.3.25 for any reason can use that one. 

And then shortly after, removing all hacks and compatibility code with this PR, and tag a new version of mpi4jax that requires jax v0.3.25. Could even be a major new release...

**Comment by dionhaefner** [comment]
Yea thanks for the suggestion but I'm not really interested in backporting stuff. This bug has been present since day 1 and this is the first time someone reported it, so probably not something that happens a lot.

Dropping older releases is fine with me.

**Comment by PhilipVinc** [comment]
I'll try right away

**Comment by PhilipVinc** [comment]
the tests for collective ops pass, but the "test_examples.py" is deadlocking. I'll look into it.

**Comment by dionhaefner** [comment]
That is... suspicious 😅 

But OK, thanks. I will implement the other ops then, and will ping you for another round of tests.

**Comment by dionhaefner** [comment]
Done but untested on GPU. @PhilipVinc your move

**Comment by PhilipVinc** [comment]
i see a room failure...

``python
filippovicentini in mpi4jax at cqslpc1 on  mlir [$] via python-3.10.6 via 🐍 3.10.6
➜ JAX_PLATFORMS="gpu" pytest --tb=short
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
MPI vendor: ('Open MPI', (4, 1, 2))
MPI rank: 0
MPI size: 1
rootdir: /home/filippovicentini/Dropbox/Ricerca/Codes/Python/mpi4jax, configfile: pyproject.toml, testpaths: tests
plugins: cov-4.0.0
collected 97 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________ ERROR collecting tests/collective_ops/test_allreduce_matvec.py ______________________________________________________
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/lib/xla_bridge.py:333: in backends
    backend = _init_backend(platform)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/lib/xla_bridge.py:385: in _init_backend
    backend = factory()
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/lib/xla_bridge.py:229: in make_gpu_client
    return xla_client.make_gpu_client(
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jaxlib/xla_client.py:91: in make_gpu_client
    return _xla.get_gpu_client(
E   jaxlib.xla_extension.XlaRuntimeError: NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA Interpreter Host

During handling of the above exception, another exception occurred:
tests/collective_ops/test_allreduce_matvec.py:15: in <module>
    k1, k2, k3, k4, k5 = jax.random.split(jax.random.PRNGKey(seed), 5)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/random.py:132: in PRNGKey
    key = prng.seed_with_impl(impl, seed)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/prng.py:267: in seed_with_impl
    return random_seed(seed, impl=impl)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/prng.py:577: in random_seed
    seeds_arr = jnp.asarray(np.int64(seeds))
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py:2028: in asarray
    return array(a, dtype=dtype, copy=False, order=order)  # type: ignore
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py:2009: in array
    out_array: Array = lax_internal._convert_element_type(out, dtype, weak_type=weak_type)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/lax/lax.py:594: in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/core.py:329: in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/core.py:332: in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/core.py:712: in process_primitive
    return primitive.impl(*tracers, **params)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/dispatch.py:113: in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/util.py:253: in wrapper
    return cached(config._trace_context(), *args, **kwargs)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/util.py:246: in cached
    return f(*args, **kwargs)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/dispatch.py:197: in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), device, None,
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/dispatch.py:359: in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/profiler.py:314: in wrapper
    return func(*args, **kwargs)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/dispatch.py:473: in lower_xla_callable
    backend = xb.get_device_backend(device) if device else xb.get_backend(backend)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/lib/xla_bridge.py:425: in get_backend
    return _get_backend_uncached(platform)
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/lib/xla_bridge.py:409: in _get_backend_uncached
    bs = backends()
../../../../../Documents/pythonenvs/mpi4jax/python-3.10.6/lib/python3.10/site-packages/jax/_src/lib/xla_bridge.py:350: in backends
    raise RuntimeError(err_msg)
E   RuntimeError: Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA Interpreter Host (set JAX_PLATFORMS='' to automatically choose an available backend)
========================================================================= short test summary info ==========================================================================
ERROR tests/collective_ops/test_allreduce_matvec.py - RuntimeError: Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA Interpreter Host...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 1.87s =============================================================================
```

**Comment by PhilipVinc** [comment]
I see lots of failures with 

```python
FAILED tests/experimental/test_auto_tokenize.py::test_while_loop_tokenizer - jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: No registered implementation for custom call to "mpi_allreduce"
FAILED tests/experimental/test_auto_tokenize.py::test_cond_tokenizer - jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: No registered implementation for custom call to "mpi_allreduce"
FAILED tests/experimental/test_auto_tokenize.py::test_allgather_scalar - jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: No registered implementation for custom call to "mpi_allgather"
FAILED tests/experimental/test_auto_tokenize.py::test_alltoall_jit - jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: No registered implementation for custom call to "mpi_alltoall"
FAILED tests/experimental/test_auto_tokenize.py::test_bcast_scalar_jit - jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: No registered implementation for custom call to "mpi_bcast"
FAILED tests/experimental/test_auto_tokenize.py::test_gather_scalar_jit - AttributeError: 'HashableMPIType' object has no attribute 'Get_rank'
FAILED tests/experimental/test_auto_tokenize.py::test_reduce_scalar_jit - jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: No registered implementation for custom call to "mpi_reduce"
FAILED tests/experimental/test_auto_tokenize.py::test_scan_scalar_jit - jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: No registered implementation for custom call to "mpi_scan"
FAILED tests/experimental/test_auto_tokenize.py::test_scatter_jit - jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: No registered implementation for custom call to "mpi_scatter"
```

**Comment by dionhaefner** [comment]
I fixed the issue with `gather` and took a stab at the other failures. Could you try again please?

**Comment by PhilipVinc** [comment]
works now and passes all tests!

**Pull request merged**
