### PR TITLE
Fix inconsistent output shapes

### PR DESCRIPTION
**Pull request by dionhaefner**
I've noticed [some CI failures](https://github.com/team-ocean/veros/runs/4999722412?check_suite_focus=true#step:14:258). Apparently JAX has gotten stricter with validating output shapes of primitives (which is a good thing).

### CODE REVIEW

**Comment by PhilipVinc** [comment]
(might be a good idea to maybe setup a github action to run on jax releases and make an issue if it fails, if we ever get the time)

**Comment by dionhaefner** [comment]
Should be handled via `dependabot` now (we get a PR on JAX version bumps).

**Comment by PhilipVinc** [comment]
In my experience dependabot only tracks the dependencies in setup.py/pyproject.toml and their bounds.
So if you upper bound jax to 0.2.X and they release 0.2.x+1 you get a dependabot PR.
If your upper bound is 0.3 you don't get it.

**Comment by dionhaefner** [comment]
I added a dummy `.txt` file with a pinned JAX version for dependabot to bump, so I'm pretty sure this is going to work.

**Comment by PhilipVinc** [comment]
great then! 

Should we mark a new release? (by the way, do you have a vague idea of what version of jax broke `mpi4jax`?)

**Comment by dionhaefner** [comment]
Must be the latest one, this should have bubbled up earlier otherwise. I'll make a release.

**Pull request merged**
