### PR TITLE
Reduce operation enabled

### PR DESCRIPTION
**Pull request by jczaja**
Implemented MPI_Reduce operation for XPU

### CODE REVIEW

**Comment by dionhaefner** [comment]
?

**Comment by PhilipVinc** [comment]
@dionhaefner did you ever get the the emails I sent you with Intel people? I realize now it was your academic email and might be expired

**Comment by dionhaefner** [comment]
Nope, that one's dead 😅

**Comment by PhilipVinc** [comment]
Send me an email with the correct one.

**Comment by jczaja** [comment]
@PhilipVinc , @dionhaefner  I appologize for this PR as it was created by mistake. It was suppose to be done to our own fork and only then when all is verified to we are to make PR to this repo. So we are working but no PR to this repo yet.

**Pull request closed without merging**
