### PR TITLE
Fix #229

### LINKED ISSUE #229: Unexpected behavior with JIT'ing allreduce
I've encountered a strange behavior when using mpi4jax that has, in retrospect, been plaguing me for months.  I've managed to put it into a reproducer here:

https://gist.github.com/coreyjadams/6640c00c3dc0f202989cc964b8995214

(UPDATE: Here is an even simpler reproducer: 
https://gist.github.com/coreyjadams/3491879671467a72f102e2407d1890ee - I am able to make a buffer size large enough repeated allreduce breaks)

This code is standalone, you can just run it with `mpirun -n 1 python cg_test.py`.  It runs a Conjugate Gradient solve on synthetic data, where the use case is we have a factorization of the matrix A (of Ax=b fame) into a jacobian of shape (n_samples, n_params).  I have noticed that if the number of parameters (n_params) is small enough, mpi4jax works alright.  Above a threshold, it starts to produce strange results but ONLY if I use JIT.  I even tried introducing an mpi barrier to force the `allreduce` operation to complete - assuming I am using the tokens correctly - and that has not succeeded.

I found in some tests that the parameter size of 11963 was a turning point for when the CG algorithm really started breaking down, which is why I'm using it below, but it seems to be a red herring.  The real situation appears to be that jitting this allreduce produces unstable results: you will get different numbers running this script repeatedly, but ONLY in the situation of using mpi4jax's allreduce AND applying JIT to it.

I've reproduced this on two different systems using CUDA GPUs and seen it both times.  I've tested on CPU and it worked exactly as expected.

Summary: mpi4jax's `allreduce` function appears to have a bug when using data on CUDA gpus (routing through the CPU, in this case, haven't tested GPU-aware MPI) when JIT is applied.

If you run that out of the box,  you'll get these results:
```bash
NO  JIT - MPI: True, n_params: 11962, residual: 3.157265166369743.
YES JIT - MPI: True, n_params: 11962, residual: 9.479986947810453.
NO  JIT - MPI: True, n_params: 11963, residual: 3.549211138934023.
YES JIT - MPI: True, n_params: 11963, residual: 8.920987131893863.
NO  JIT - MPI: False, n_params: 11962, residual: 3.157265166369743.
YES JIT - MPI: False, n_params: 11962, residual: 3.1572651663697435.
NO  JIT - MPI: False, n_params: 11963, residual: 3.549211138934023.
YES JIT - MPI: False, n_params: 11963, residual: 3.549211138934023.
```

If you increase the number of iterations to 500, you get this:
```bash
No  JIT - MPI: True, n_params: 11962, residual: 0.00018166722894453279.
YES JIT - MPI: True, n_params: 11962, residual: 257.7061756863171.
NO  JIT - MPI: True, n_params: 11963, residual: 0.00014933259546807327.
YES JIT - MPI: True, n_params: 11963, residual: 211.88027991643523.
NO  JIT - MPI: False, n_params: 11962, residual: 0.00018166722894453279.
YES JIT - MPI: False, n_params: 11962, residual: 0.0001816672289445146.
NO  JIT - MPI: False, n_params: 11963, residual: 0.00014933259546807327.
YES JIT - MPI: False, n_params: 11963, residual: 0.0001493325954680718.
```

### PR DESCRIPTION
**Pull request by dionhaefner**

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Interesting find! Do you know why this works, and why the synchronisation is not enough?

As for the CUDA-aware MPI, maybe we could leave the explicit synchronisation in an `else:` statement, executed only when we are using CUDA?

Ps: Is it possible to enqueue in a steam a callback that executes the MPI call? That way we could do everything truly async.

**Comment by dionhaefner** [comment]
Yea I have no clue really. Enqueuing MPI ops would require us to get a pointer to the function to call and somehow also pass the arguments along, sounds like a bigger project to me.

This behavior makes me suspect that XLA is not using the [cudaDeviceScheduleBlockingSync flag](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g057e6912c52708b6aa86e79dd83d007c) so calls to synchronize are not actually blocking? Even when I do `cudaDeviceSynchronize` I get the same behavior, even though that should synchronize the entire device including all streams...

**Comment by dionhaefner** [comment]
Ok so yes it looks like `cudaMemcpy` is not actually blocking in our case. These work:

```python
# ok
cudaMemcpy(dst, src, count, kind)
cudaDeviceSynchronize()

# also ok
cudaMemcpyAsync(dst, src, count, kind, stream)
cudaStreamSynchronize(stream)

# also ok
cudaMemcpy(dst, src, count, kind)
cudaStreamSynchronize(<cudaStream_t>0)  # <- uses default stream!
```

Whereas these don't:

```python
cudaMemcpy(dst, src, count, kind)  # not ok
cudaStreamSynchronize(stream)  # <- syncs wrong stream

cudaMemcpy(dst, src, count, kind)  # also not ok
# missing sync, doesn't wait for memcpy to complete
```

I thought the critical piece was to sync *before* starting the memcpy, but turns out we need to sync *after*.

**Comment by dionhaefner** [comment]
What's implemented now should work for all cases but I couldn't test with CUDA MPI. Would be great if anyone else could do that.

**Comment by dionhaefner** [comment]
@PhilipVinc You want to validate this on your NetKet setup on GPU before merging? Not sure if I broke anything when CUDA MPI is used.

**Comment by PhilipVinc** [comment]
I just tried running it, but the direct CUDA setup I have easy access to is broken. They are trying to fix the setup but will take a few days.

**Comment by dionhaefner** [comment]
@PhilipVinc Should we merge? Fixing this bug probably has higher priority than the off chance that I broke CUDA MPI.

**Comment by PhilipVinc** [comment]
I'd say let's merge and see what happens.

**Pull request merged**
