### PR TITLE
Fix for mpi4py>=4

### PR DESCRIPTION
**Pull request by dionhaefner**

### CODE REVIEW

**Comment by dionhaefner** [comment]
@PhilipVinc Any idea what's going on with the XPU build?

**Comment by PhilipVinc** [comment]
@jczaja  @Zantares @Dboyqiao Do you know why the XPU build is failing? We're trying to update to mpi4py version 4.0 and changed the way we look for the mpicc compilers

**Comment by Dboyqiao** [comment]
> @jczaja @Zantares @Dboyqiao Do you know why the XPU build is failing? We're trying to update to mpi4py version 4.0 and changed the way we look for the mpicc compilers
> 
> see https://github.com/mpi4jax/mpi4jax/actions/runs/10417415662/job/28851620468?pr=253#step:8:408

Hi @PhilipVinc I have checked the log, in this patch, the build toolchain is changed from /usr/bin/mpicc to g++, which cause the build failure.
`g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DOMPI_SKIP_MPICXX=1 -I/home/runner/basekit/compiler/2024.0/include/ -I/home/runner/basekit/compiler/2024.0/include/sycl -I/opt/hostedtoolcache/Python/3.12.4/x64/include/python3.12 -c mpi4jax/_src/xla_bridge/mpi_xla_bridge_xpu.cpp -o build/temp.linux-x86_64-cpython-312/mpi4jax/_src/xla_bridge/mpi_xla_bridge_xpu.o`

**Comment by dionhaefner** [comment]
It's setuptools, seems like there were some internal changes to the CXX compiler variable isn't obeyed anymore. I'll dig through the changelog and see if I can fix it.

**Comment by PhilipVinc** [comment]
yep, seems that was that

**Review by PhilipVinc — APPROVED** [review]

**Pull request merged**
